apiVersion: v1
kind: ConfigMap
metadata:
  name: piraeus-node
  namespace: piraeus-system
data:
  INIT_DEBUG: "false"
  LS_CONTROLLERS: piraeus-controller.piraeus-system.svc.cluster.local:3370
  POOL_BASE_DIR: /var/lib/piraeus/storagepools
  DRBD_IMG_TAG: v9.0.21
  DRBD_IMG_PULL_POLICY: IfNotPresent
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: piraeus-node
  namespace: piraeus-system
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: piraeus
      app.kubernetes.io/component: piraeus-node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piraeus
        app.kubernetes.io/component: piraeus-node
    spec:
      restartPolicy: Always
      hostNetwork: true
      hostPID: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: oci
        image: daocloud.io/piraeus/piraeus-oci:v0.1
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: piraeus-node
        env:
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: systemd
          mountPath: /etc/systemd/system
        - name: lib-linstor-d
          mountPath: /var/lib/linstor.d
        - name: etc-linstor
          mountPath: /etc/linstor
        - name: usr-src
          mountPath: /usr/src
        - name: lib-modules
          mountPath: /lib/modules
        - name: opt-piraeus
          mountPath: /opt/piraeus
        readinessProbe:
          successThreshold: 3
          failureThreshold: 3
          tcpSocket:
            port: 3366
          periodSeconds: 5
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Etc/UTC
      - name: opt-piraeus
        hostPath:
          path: /opt/piraeus
      - name: var-lib-piraeus
        hostPath:
          path: /var/lib/piraeus
      - name: lib-linstor-d
        hostPath:
          path: /var/lib/linstor.d
      - name: etc-linstor
        hostPath:
          path: /etc/linstor
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: systemd
        hostPath:
          path: /etc/systemd/system
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: lib-modules
        hostPath:
          path: /lib/modules
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: piraeus/node
                operator: In
                values:
                - "true"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
