#@ load("funcs.lib.yml", "map_host_linstor", "map_host_lvm", "name", "namespace", "timezone", "node", "initimage", "controllerhostport", "registry", "controllerimage", "satelliteimage", "set_priority_class")
apiVersion: v1
kind: ConfigMap
metadata:
  name: #@ node()
  namespace: #@ namespace()
data:
  INIT_DEBUG: 'false'
  #! Must be an FQDN here, otherwise it might not resolve!
  LS_CONTROLLERS: #@ controllerhostport()
  POOL_BASE_DIR: #@ "/var/lib/" + name() + "/storagepools"
  DRBD_IMG_TAG: v9.0.21 #! "none" will skip drbd installation
  DRBD_IMG_PULL_POLICY: IfNotPresent
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: #@ node()
  namespace: #@ namespace()
spec:
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: #@ name()
      app.kubernetes.io/component: #@ node()
  template:
    metadata:
      labels:
        app.kubernetes.io/name: #@ name()
        app.kubernetes.io/component: #@ node()
    spec:
      #@ if set_priority_class():
      priorityClassName: system-node-critical
      #@ end
      restartPolicy: Always
      hostNetwork: true
      hostPID: true
      hostIPC: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: oci
        image: daocloud.io/piraeus/piraeus-oci:v0.1
        imagePullPolicy: Always
        securityContext:
          privileged: true
        resources:
          #! requests:
          #!   cpu: 100m
          #!   memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name:  #@ node()
        env:    
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: systemd
          mountPath: /etc/systemd/system
        - name: lib-linstor-d
          mountPath: /var/lib/linstor.d
        - name: etc-linstor
          mountPath: /etc/linstor
        - name: usr-src
          mountPath: /usr/src
        - name: lib-modules
          mountPath: /lib/modules
        - name: #@ "opt-" + name()
          mountPath: #@ "/opt/" + name()
        readinessProbe:
          successThreshold: 3
          failureThreshold: 3
          tcpSocket:
            port: 3366
          periodSeconds: 5
      volumes:
      - name: timezone
        hostPath:
          path: #@ timezone()
      - name: #@ "opt-" + name()
        hostPath:
          path: #@ "/opt/" + name()
      - name: #@ "var-lib-" + name()
        hostPath:
          path: #@ "/var/lib/" + name()
      - name: lib-linstor-d
        hostPath:
          path: /var/lib/linstor.d
      - name: etc-linstor
        hostPath:
          path: /etc/linstor
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: systemd
        hostPath:
          path: /etc/systemd/system
      - name: usr-src
        hostPath:
          path: /usr/src
      - name: lib-modules
        hostPath:
          path: /lib/modules
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: #@ name() + "/node"
                operator: In
                values:
                  - "true"
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      tolerations:
      - operator: Exists
        effect: NoSchedule
      - key: CriticalAddonsOnly
        operator: Exists
      #! imagePullSecrets:
      #! - name: piraeus-regcred
